### ISSUE TITLE
v8.6.9 updates

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#687]
Based on [v8.6.9 RC Announcement](https://community.notepad-plus-plus.org/topic/25918/notepad-v8-6-9-release-candidate), these are the items that likely affect user manual:

- [x] 1. Make installation and updates easy & quiet by adding "Yes (Silent)" button. (Fix [#8514](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8514)) ⇒ #681
- [x] 2. Add new options '/closeRunningNpp' & '/runNppAfterSilentInstall' in the installer. (Implement [#15230](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15230), implement [#15280](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15280))  ⇒ #681
- [x] 7. Prevent DirectWrite from being enabled under Windows Sever. ([commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6b441b738a951ed225632f4085a46c95cd4aa13f))
- [x] 11. Add ability to pre-populate the predefined color sets for custom tones. (Fix [#15055](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15055))
- [x] 12. Add "Show All Character" popup menu on toolbar button. (Fix [#14832](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14832))
- [x] 16. Add Backspace unindent option. (Fix [#15180](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15180))
- [x] 18. Include F13-F24 keys in Shortcut Mapper. (Fix [#11975](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11975))
- [x] 20. Add plugin a command (NPPM_SETUNTITLEDNAME) to rename untitled tab. (Fix [#8916](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8916)) ⇒ #680

**Comment by pryrt** [comment]
item 18: the manual doesn't list available keys; I updated [Guy's FAQ entry](https://community.notepad-plus-plus.org/post/56067) instead.
